import type { Database } from "sql.js";
import { query } from "../storage/query.js";

interface FeatureRow {
  id: string;
  name: string;
  status: string;
  priority: string;
  description: string | null;
  session_claimed: string | null;
  claimed_at: string | null;
  completed_at: string | null;
}

interface ClaimRow {
  feature_id: string;
  feature_name: string;
  session_id: string;
  claimed_at: string;
}

interface DecisionRow {
  session_id: string;
  description: string;
  rationale: string | null;
}

interface SessionRow {
  id: string;
  agent: string;
  started_at: string;
  ended_at: string | null;
  summary: string | null;
}

export function generateProjectState(
  db: Database,
  projectName: string
): string {
  const now = new Date().toISOString().slice(0, 10);

  const features = query<FeatureRow>(db, "SELECT * FROM features ORDER BY created_at");

  const activeClaims = query<ClaimRow>(
    db,
    `SELECT c.feature_id, f.name as feature_name, c.session_id, c.claimed_at
     FROM claims c JOIN features f ON c.feature_id = f.id
     WHERE c.released_at IS NULL`
  );

  const available = query<FeatureRow>(
    db,
    `SELECT f.* FROM features f
     WHERE f.status = 'pending'
     AND f.id NOT IN (SELECT feature_id FROM claims WHERE released_at IS NULL)
     ORDER BY CASE f.priority
       WHEN 'critical' THEN 0 WHEN 'high' THEN 1
       WHEN 'medium' THEN 2 WHEN 'low' THEN 3
     END`
  );

  const decisions = query<DecisionRow>(
    db,
    "SELECT d.session_id, d.description, d.rationale FROM decisions d ORDER BY d.created_at"
  );

  const sessions = query<SessionRow>(
    db,
    "SELECT * FROM sessions ORDER BY started_at DESC"
  );

  const lastSession = sessions[0];
  const done = features.filter((f) => f.status === "done");
  const blocked = features.filter((f) => f.status === "blocked");

  let md = `# ${projectName} — Product State\n`;
  md += `Last updated: ${now}`;
  if (lastSession) {
    md += ` | Last session: ${lastSession.id}`;
  }
  if (features.length > 0) {
    const pct = Math.round((done.length / features.length) * 100);
    md += ` | Progress: ${pct}%`;
  }
  md += "\n\n";

  if (done.length > 0) {
    md += "## What's been built\n";
    for (const f of done) {
      md += `- ${f.name}`;
      if (f.completed_at) md += ` (completed ${String(f.completed_at).slice(0, 10)})`;
      md += "\n";
    }
    md += "\n";
  }

  if (activeClaims.length > 0) {
    md += "## Currently claimed\n";
    for (const claim of activeClaims) {
      md += `- ${claim.feature_name} → session ${claim.session_id} (started ${claim.claimed_at})\n`;
    }
    md += "\n";
  }

  if (available.length > 0) {
    md += "## Available next\n";
    for (const f of available) {
      md += `- ${f.name} (priority: ${f.priority})`;
      if (f.description) md += ` — ${f.description}`;
      md += "\n";
    }
    md += "\n";
  }

  if (blocked.length > 0) {
    md += "## Blocked\n";
    for (const f of blocked) {
      md += `- ${f.name}`;
      if (f.description) md += ` — ${f.description}`;
      md += "\n";
    }
    md += "\n";
  }

  if (decisions.length > 0) {
    md += "## Architecture log\n";
    for (const d of decisions) {
      md += `- ${d.session_id}: ${d.description}`;
      if (d.rationale) md += ` — ${d.rationale}`;
      md += "\n";
    }
    md += "\n";
  }

  if (sessions.length > 0) {
    md += "## Recent sessions\n";
    for (const s of sessions.slice(0, 10)) {
      const status = s.ended_at ? "done" : "active";
      md += `- ${s.id} (${s.agent}, ${status})`;
      if (s.summary) md += ` — ${s.summary}`;
      md += "\n";
    }
    md += "\n";
  }

  return md;
}

export function generateAgentsMd(
  db: Database,
  projectName: string
): string {
  const available = query<FeatureRow>(
    db,
    `SELECT f.name, f.priority, f.description FROM features f
     WHERE f.status = 'pending'
     AND f.id NOT IN (SELECT feature_id FROM claims WHERE released_at IS NULL)
     ORDER BY CASE f.priority
       WHEN 'critical' THEN 0 WHEN 'high' THEN 1
       WHEN 'medium' THEN 2 WHEN 'low' THEN 3
     END`
  );

  const activeClaims = query<ClaimRow>(
    db,
    `SELECT f.name as feature_name, c.session_id
     FROM claims c JOIN features f ON c.feature_id = f.id
     WHERE c.released_at IS NULL`
  );

  let md = `# ${projectName} — Agent Instructions\n\n`;
  md += "This file is auto-generated by groundctl. Read it before starting work.\n\n";

  md += "## Before you start\n";
  md += "1. Read PROJECT_STATE.md for full product context\n";
  md += "2. Run `groundctl next` to see available features\n";
  md += "3. Run `groundctl claim <feature>` to reserve your work\n";
  md += "4. When done, run `groundctl complete <feature>`\n";
  md += "5. Run `groundctl sync` to update state files\n\n";

  if (activeClaims.length > 0) {
    md += "## Do NOT work on (already claimed)\n";
    for (const c of activeClaims) {
      md += `- ${c.feature_name} (session ${c.session_id})\n`;
    }
    md += "\n";
  }

  if (available.length > 0) {
    md += "## Available to claim\n";
    for (const f of available) {
      md += `- ${f.name} (${f.priority})`;
      if (f.description) md += ` — ${f.description}`;
      md += "\n";
    }
    md += "\n";
  }

  return md;
}
